export default {
  AUTH_LOGIN: 'WMS_AUTH_LOGIN',
  AUTH_ERROR: 'WMS_AUTH_ERROR',
  AUTH_LOGOUT: 'WMS_AUTH_LOGOUT',
  AUTH_REGISTER: 'WMS_AUTH_REGISTER',
  AUTH_RESET_PASSWORD: 'WMS_AUTH_RESET_PASSWORD',
  AUTH_VERIFY: 'WMS_AUTH_VERIFY',
  AUTH_SET_TOKEN: 'WMS_AUTH_SET_TOKEN'

};
